// solid-version/src/hooks/useWidth.ts
import { createSignal, onCleanup } from "solid-js"

const getWidth = () => document.documentElement.getBoundingClientRect().width

export function useWidth() {
	const [width, setWidth] = createSignal(getWidth())
	const resize = () => setWidth(getWidth())
	addEventListener('resize', resize)
	onCleanup(() => removeEventListener('resize', resize))

	return width
}

// react-version/src/hooks/useWidth.ts
import { useSyncExternalStore } from "react"

const getWidth = () => document.documentElement.getBoundingClientRect().width

const subscribe = (callback: () => void) => {
	addEventListener('resize', callback)
	return () => removeEventListener('resize', callback)
}

export const useWidth = () => useSyncExternalStore(subscribe, getWidth)
