// react-version/src/components/UpgradeMenu/index.tsx
import { upgrades, getUpgPoints } from '../../data/upgrades'
import { Character } from '../../data/stats'
import { useDropdownState } from '../../hooks/useDropdownState'
import { lazy, Suspense, useEffect, useRef, useState } from 'react'

const PerkList = lazy(() => import('./lists').then(module => ({ default: module.PerkList })))
const TempList = lazy(() => import('./lists').then(module => ({ default: module.TempList })))

export function UpgradeContainer({ upgs, owner, className, temp, updateTemp, updateUpgs }: { upgs: Set<number>, owner: Character, className: string, temp: number[], updateTemp: (newVal: number[]) => void, updateUpgs?: (newVal: Set<number>) => void }) {
	// Adding cost here instead of in UpgradeMenu so both components rerender every time
	const newCost = getUpgPoints(upgs, upgrades[owner.id])
	const [cost, setCost] = useState(newCost)
	if (newCost != cost) setCost(newCost)

	const updateCost = (newVal: number) => {
		setCost(newVal)
		updateUpgs?.(new Set(upgs))
	}

	useEffect(() => {
		const timeout = setTimeout(() => import('./lists'), 500)
		return () => clearTimeout(timeout)
	}, [])

	return <div className={className}>
		<UpgradeMenu upgs={upgs} owner={owner} cost={cost} setCost={updateCost} temp={temp} updateTemp={updateTemp} />
		<TempMenu upgs={upgs} owner={owner} temp={temp} updateTemp={updateTemp} />
	</div>
}

function UpgradeMenu({ upgs, owner, cost, setCost, temp, updateTemp }: { upgs: Set<number>, owner: Character, cost: number, setCost: (val: number) => void, temp: number[], updateTemp: (newVal: number[]) => void }) {
	const [open, setOpen] = useDropdownState('#upg')
	const elRef = useRef<HTMLDivElement>(null)

	return <div
		ref={elRef}
		className="select" id="upg"
		onKeyDown={e => {
			e.code == 'Escape' && setOpen(false)
			e.stopPropagation()
		}}
	>
		<button>Upgrades ({cost}/7)</button>
		{
			open && <Suspense fallback={<ul className='perk-list'></ul>}>
				<PerkList
					cost={cost} setCost={setCost} upgs={upgs} owner={owner}
					setOpen={setOpen} temp={temp} updateTemp={updateTemp} maxHeight={
						Math.min(innerHeight - elRef.current.getBoundingClientRect().top - 40, 532)
				}/>
			</Suspense>
		}
	</div>
}

function TempMenu({ upgs, owner, temp, updateTemp }: { upgs: Set<number>, owner: Character, temp: number[], updateTemp: (newVal: number[]) => void }) {
	const [open, setOpen] = useDropdownState('#temp')
	let isHidden = true
	for (const id of upgs) if (upgrades[owner.id][id]?.[5]) {
		isHidden = false
		break
	}

	return <div
		className="select" id="temp"
		onKeyDown={e => {
			e.code == 'Escape' && setOpen(false)
			e.stopPropagation()
		}}
		style={
			isHidden ? { visibility: 'hidden' } : {}
		}
	>
		<button>Temporary upgrades</button>
		{
			open && <Suspense fallback={<ul className='temp-list'></ul>}>
				<TempList upgs={upgs} temp={temp} owner={owner} updateTemp={updateTemp} />
			</Suspense>
		}
	</div>
}

// solid-version/src/components/UpgradeMenu/index.tsx
import { Accessor, Signal, Show, createMemo, lazy, onMount } from "solid-js";
import { getUpgPoints, upgrades } from "../../data/upgrades";
import { createParamSignal } from "../../hooks/createParamSignal";
import { useDropdownState } from "../../hooks/useDropdownState";
import { Character } from "../../data/stats";

const PerkList = lazy(() => import('./lists').then(module => ({ default: module.PerkList })))
const TempList = lazy(() => import('./lists').then(module => ({ default: module.TempList })))

export type Signal1<T> = Signal<T> | ReturnType<typeof createParamSignal<T>>

export function UpgradeContainer(props: { upgs: Signal1<Set<number>>, temp: Signal1<number[]>, owner: Accessor<Character>, class: string }) {
	const [open, setOpen] = useDropdownState('#upg')
	const [open2, setOpen2] = useDropdownState('#temp')
	const cost = createMemo(() => getUpgPoints(props.upgs[0](), upgrades[props.owner().id]))
	const showTemp = () => {
		const upgs = upgrades[props.owner().id]
		for (const id of props.upgs[0]()) {
			if (upgs[id]?.[5]) return true
		}
		return false
	}
	onMount(() => setTimeout(() => import('./lists'), 500))

	let upgContainer: HTMLDivElement
	return <div class={props.class}>
		<div
			class="select" id="upg"
			ref={upgContainer}
			onKeyDown={e => {
				e.code == "Escape" && setOpen(!open())
				e.stopPropagation()
			}}
		>
			<button>Upgrades ({cost()}/7)</button>
			<Show when={open()}>
				<PerkList {...Object.assign({ cost, setOpen, maxHeight: Math.min(innerHeight - upgContainer.getBoundingClientRect().top - 40, 532) }, props)}  />
			</Show>
		</div>
		<div
			class="select" id="temp"
			onKeyDown={e => {
				e.code == "Escape" && setOpen2(!open2())
				e.stopPropagation()
			}}
			style={
				showTemp() ? {} : { visibility: "hidden" }
			}
		>
			<button>Temporary upgrades</button>
			<Show when={open2()}>
				<TempList {...props} />
			</Show>
		</div>
	</div>
}
